version: 2.1

executors:
  python_executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  test:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run unit tests with coverage
          command: pytest --cov

  build-and-push:
    executor: python_executor
    steps:
      - checkout

      - run:
          name: Install Docker CLI (solo necesario si da error)
          command: |
            sudo apt update && sudo apt install -y docker.io

      - run:
          name: Unshallow git repo
          command: git fetch --prune --unshallow || true

      - run:
          name: Set VERSION env from tag
          command: echo "export VERSION=${CIRCLE_TAG#v}" >> $BASH_ENV

      - run:
          name: Docker login to GHCR
          command: echo "${DOCKER_PASSWORD}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin

      - run:
          name: Build and publish Docker image
          command: |
            source $BASH_ENV
            make publish

workflows:
  version: 2
  ci:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
