apiVersion: v1
kind: Pod
metadata:
  name: stress-cpu
  namespace: fast-api
  labels:
    app: stress-test
spec:
  restartPolicy: Never
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2"]
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
